var annotated =
[
    [ "Benchmarking application", "md_markdown_building.html#building_bmapp", null ],
    [ "Benchmark", "classBenchmark.html", "classBenchmark" ],
    [ "BenchmarkCFG", "classBenchmarkCFG.html", "classBenchmarkCFG" ],
    [ "Cell", "classCell.html", "classCell" ],
    [ "Class", "classClass.html", null ],
    [ "Console", "classConsole.html", null ],
    [ "console", "classconsole.html", "classconsole" ],
    [ "DDQM", "classDDQM.html", "classDDQM" ],
    [ "EikonalSolver", "classEikonalSolver.html", "classEikonalSolver" ],
    [ "FIM", "classFIM.html", "classFIM" ],
    [ "FM2", "classFM2.html", "classFM2" ],
    [ "FM2Star", "classFM2Star.html", "classFM2Star" ],
    [ "FMCell", "classFMCell.html", "classFMCell" ],
    [ "FMCompare", "structFMCompare.html", "structFMCompare" ],
    [ "FMDaryHeap", "classFMDaryHeap.html", "classFMDaryHeap" ],
    [ "FMFibHeap", "classFMFibHeap.html", "classFMFibHeap" ],
    [ "FMM", "classFMM.html", "classFMM" ],
    [ "FMMStar", "classFMMStar.html", "classFMMStar" ],
    [ "FMPriorityQueue", "classFMPriorityQueue.html", "classFMPriorityQueue" ],
    [ "FMSM", "classFMSM.html", "classFMSM" ],
    [ "FMUntidyQueue", "classFMUntidyQueue.html", "classFMUntidyQueue" ],
    [ "FSM", "classFSM.html", "classFSM" ],
    [ "GMM", "classGMM.html", "classGMM" ],
    [ "GradientDescent", "classGradientDescent.html", "classGradientDescent" ],
    [ "GridPlotter", "classGridPlotter.html", "classGridPlotter" ],
    [ "GridPoints", "classGridPoints.html", "classGridPoints" ],
    [ "GridWriter", "classGridWriter.html", "classGridWriter" ],
    [ "GridWritter", "classGridWritter.html", null ],
    [ "LSM", "classLSM.html", "classLSM" ],
    [ "MapLoader", "classMapLoader.html", "classMapLoader" ],
    [ "nDGridMap", "classnDGridMap.html", "classnDGridMap" ],
    [ "SFMM", "classSFMM.html", "classSFMM" ],
    [ "SFMMStar", "classSFMMStar.html", "classSFMMStar" ],
    [ "SFMMStarStar", "classSFMMStarStar.html", null ],
    [ "Solver", "classSolver.html", "classSolver" ],
    [ "UFMM", "classUFMM.html", "classUFMM" ]
];